[package]
name = "sankrit_vm"
version = "0.1.0"
authors = ["tawaren <markus.knecht85@gmail.com>"]

[dependencies]
lazy_static = "0.2.8"
lmdb-rs = "0.7.6"
blake2-rfc = "0.2.18"
constant_time_eq = "0.1.3"
byteorder = "1.2.1"
lazycell = "0.6.0"