[workspace]
members = [
        "sanskrit_common",
        "sanskrit_derive",
        "sanskrit_core",
        "sanskrit_deploy",
        "sanskrit_interpreter",
        "sanskrit_runtime",
        "sanskrit_compile",
        "sanskrit_memory_store",
        "sanskrit_sled_store",
        "sanskrit_local_server",
        # "sanskrit_wasm_deploy_compile", #Should be compiled seperately with the wasm target
]

[profile.release]
panic = "abort"
#lto = "fat" crashes at runtime
#lto = "thin" crashes at runtime as well now
lto = false
debug = false
opt-level = 3
