[workspace]
members = [
        "sanskrit_common",
        "sanskrit_derive",
        "sanskrit_core",
        "sanskrit_deploy",
        "sanskrit_interpreter",
        "sanskrit_runtime",
        "sanskrit_compile",
        "sanskrit_memory_store",
        "sanskrit_sled_store",
        "sanskrit_test_script_compiler",
        "sanskrit_test",
        "sanskrit_local_server",
        "sanskrit_bench",
        "sanskrit_wasm_deploy_compile",
        "sanskrit_wasm_runner",
        # "sanskrit_pallet",
]

[profile.release]
panic = "abort"
lto = true
debug = false
opt-level = 3
