[package]
name = "sanskrit_sled_store"
version = "0.1.0"
authors = ["tawaren <markus.knecht85@gmail.com>"]

[dependencies.sanskrit_common]
path = "../sanskrit_common"
version = "0.1.0"

[dependencies]
sled = "0.34.7"
arrayref = "0.3.6"