[package]
name = "sanskrit_interpreter"
version = "0.1.0"
authors = ["tawaren <markus.knecht85@gmail.com>"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
panic = 'abort'

[features]
default = ["std"]
std = []

[dependencies]
byteorder = { version = "1.2.6", features = ["i128"], default-features = false }
num-traits = { version = "0.2", default-features = false}

[dependencies.sanskrit_common]
path = "../sanskrit_common"
version = "0.1.0"
default-features = false

[dependencies.sanskrit_derive]
path = "../sanskrit_derive"
version = "0.1.0"
