[package]
name = "sanskrit_derive"
version = "0.1.0"
authors = ["tawaren <markus.knecht85@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
proc-macro2 = "1.0.52"

[dependencies.syn]
version = "1.0.109"
features = ["full", "visit", "extra-traits"]
