[package]
name = "sanskrit_derive"
version = "0.1.0"
authors = ["tawaren <markus.knecht85@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "1.0.48"
quote = "1.0.7"
proc-macro2 = "1.0.24"