[package]
name = "sanskrit_memory_store"
version = "0.1.0"
authors = ["tawaren <markus.knecht85@gmail.com>"]
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies.sanskrit_common]
path = "../sanskrit_common"
version = "0.1.0"

