[package]
name = "sanskrit_local_server"
version = "0.1.0"
authors = ["tawaren <markus.knecht85@gmail.com>"]

[dependencies]
rustyline = "3.0.0"
ed25519-dalek = "0.8.1"
sha2 = "0.7.0"
rand = "0.6.1"
sled = "0.16.11"
hex = "0.3.2"
arrayref = "0.3.5"
blake2-rfc = "0.2.18"

[dependencies.sanskrit_test_script_compiler]
path = "../sanskrit_test_script_compiler"
version = "0.1.0"

[dependencies.sanskrit_compile]
path = "../sanskrit_compile"
version = "0.1.0"

[dependencies.sanskrit_deploy]
path = "../sanskrit_deploy"
version = "0.1.0"

[dependencies.sanskrit_runtime]
path = "../sanskrit_runtime"
version = "0.1.0"

[dependencies.sanskrit_common]
path = "../sanskrit_common"
version = "0.1.0"

[dependencies.sanskrit_core]
path = "../sanskrit_core"
version = "0.1.0"

[dependencies.sanskrit_sled_store]
path = "../sanskrit_sled_store"
version = "0.1.0"
