grow_memory = 90

[primitives]
get = 6
set = 6
tee = 6
load = 6
#we do not have this in ewasm spec so we use same as load for now - should just be a move in the other direction
store = 6
block = 0
loop = 0
if = 4
#shall we set 0 -- we always make exactly one jump on a if either the if or the else?
else = 4
end = 0
br = 4
br_if = 6
br_table = 4
return = 4
call = 4
const = 0
add = 2
sub = 2
mul = 6
div = 160
rem = 160
and = 2
or = 2
xor = 2
shl = 3
shr = 3
rot = 4
compare = 2
clz = 210
ctz = 210
#we do not have this in ewasm but if natively implemented it has 3 cycles
popcnt = 6
convert = 6
drop = 6
select = 6
unreachable = 0
#this is handled by grow memory in top scope -- make this skipable
grow_memory = 0

#we do not expect any indirect calls or floationgpoints and compiler should eliminate nop
call_indirect = false
float = false
nop = false

[externals]
default = 1