[package]
name = "sanskrit_compile"
version = "0.1.0"
authors = ["tawaren <markus.knecht85@gmail.com>"]
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
sp1-zkvm = { version = "3.0.0" }
serde = { version = "1.0.210", features = ["derive"] }
clap = { version = "4.5.20", features = ["derive"] }


[dependencies.sanskrit_chain_code]
path = "../sanskrit_chain_code"
version = "0.1.0"
default-features=false

[dependencies.sanskrit_common]
path = "../sanskrit_common"
version = "0.1.0"
default-features = false

[dependencies.sanskrit_core]
path = "../sanskrit_core"
version = "0.1.0"

[dependencies.sp1_zkvm_col]
path = "../sp1_zkvm_col"
version = "0.1.0"
